spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: someClientId
            client-secret: someClientSecret
  data:
    cassandra:
      keyspace-name: main
      username: someUsername
      password: somePassword
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: someId
  region: us-east1
  keyspace: main
  application.token: someToken

datastax.astra:
  secure-connect-bundle: secure-connect.zip
